apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
name: webhook-test
spec:
groups:
  - system:authenticated
    request: ""
    signerName: kubernetes.io/kube-apiserver-client
    usages:
  - digital signature
  - key encipherment
  - client auth