apiVersion: v1
kind: Service
metadata:
  labels:
    name: test
  name: test
  namespace: {{.ObjectMeta.Namespace}}
spec:
  selector:
    app: test
  ports:
    - name: {{.Spec.Template.Spec.Containers[0].Ports[0].Name}}
      protocol: {{.Spec.Template.Spec.Containers[0].Ports[0].Protocol}}
      port: {{.Spec.Template.Spec.Containers[0].Ports[0].ContainerPort}}
      targetPort: {{.Spec.Template.Spec.Containers.Ports.ContainerPort}}
    - name: {{.Spec.Template.Spec.Containers[0].Ports[1].Name}}
      protocol: {{.Spec.Template.Spec.Containers[0].Ports[1].Protocol}}
      port: {{.Spec.Template.Spec.Containers[0].Ports[1].ContainerPort}}
      targetPort: {{.Spec.Template.Spec.Containers[0].Ports[1].ContainerPort}}
  type: ClusterIP