apiVersion: rocketmq.apache.org/v1alpha1
kind: NameService
metadata:
  name: name-service
spec:
  size: 1
  nameServiceImage: open-registry.going-link.com/zhenyun/rocketmq-namesrv:4.3.2
  imagePullPolicy: Always
  hostNetwork: false
  dnsPolicy: ClusterFirstWithHostNet
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  storageMode: StorageClass
  hostPath: /data/rocketmq/nameserver
  volumeClaimTemplates:
    - metadata:
        name: namesrv-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-provisioner
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
    name: rocketmq-svc
spec:
  selector:
    statefulset.kubernetes.io/pod-name: name-service-0
  type: ClusterIP
  ports:
    - name: name-service-0
      port: 9876
      targetPort: 9876

 