apiVersion: rocketmq.apache.org/v1alpha1
kind: Console
metadata:
  name: console
spec:
  # nameServers is the [ip:port] list of name service
  nameServers: "rocketmq-svc:9876"
  # consoleDeployment define the console deployment
  consoleDeployment:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: rocketmq-console
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rocketmq-console
      template:
        metadata:
          labels:
            app: rocketmq-console
        spec:
          containers:
            - name: console
              image: open-registry.going-link.com/zhenyun/rocketmq-console:2.0.0
              ports:
                - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: console-service
  labels:
    app: rocketmq-console
spec:
  type: NodePort
  selector:
    app: rocketmq-console
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31241